"""Prometheus/VictoriaMetrics metrics for AI SRE system observability.

Exposes agent performance, tool usage, token consumption, and cost
metrics for monitoring the AI SRE system itself.
"""

from prometheus_client import Counter, Histogram, Gauge, Info

# --- Agent Performance Metrics ---

ai_sre_investigation_duration_seconds = Histogram(
    "ai_sre_investigation_duration_seconds",
    "Duration of agent investigations in seconds",
    labelnames=["agent_role"],
    buckets=[5, 10, 30, 60, 120, 180, 300, 600],
)

ai_sre_investigation_total = Counter(
    "ai_sre_investigation_total",
    "Total number of agent investigations",
    labelnames=["agent_role", "outcome"],
)

ai_sre_tool_calls_total = Counter(
    "ai_sre_tool_calls_total",
    "Total number of MCP tool calls",
    labelnames=["tool_name", "agent_role"],
)

ai_sre_tool_call_duration_seconds = Histogram(
    "ai_sre_tool_call_duration_seconds",
    "Duration of individual MCP tool calls in seconds",
    labelnames=["tool_name"],
    buckets=[0.1, 0.5, 1, 2, 5, 10, 30],
)

# --- Token and Cost Metrics ---

ai_sre_tokens_used_total = Counter(
    "ai_sre_tokens_used_total",
    "Total tokens consumed by agent invocations",
    labelnames=["model", "agent_role"],
)

ai_sre_api_cost_dollars = Counter(
    "ai_sre_api_cost_dollars",
    "Estimated Anthropic API cost in USD",
    labelnames=["model"],
)

# --- Alert Processing Metrics ---

ai_sre_alerts_processed_total = Counter(
    "ai_sre_alerts_processed_total",
    "Total alerts processed by the AI SRE system",
    labelnames=["severity", "cluster"],
)

ai_sre_advisories_generated_total = Counter(
    "ai_sre_advisories_generated_total",
    "Total advisories generated by agents",
    labelnames=["agent_role"],
)

# --- Approval Metrics ---

ai_sre_approvals_total = Counter(
    "ai_sre_approvals_total",
    "Total approval workflow actions",
    labelnames=["action", "outcome"],
)

# --- Error Metrics ---

ai_sre_errors_total = Counter(
    "ai_sre_errors_total",
    "Total errors encountered by agents",
    labelnames=["agent_role", "error_type"],
)

# --- System Health Gauges ---

ai_sre_active_investigations = Gauge(
    "ai_sre_active_investigations",
    "Number of currently active investigations",
)

ai_sre_circuit_breaker_state = Gauge(
    "ai_sre_circuit_breaker_state",
    "Circuit breaker state (0=closed, 1=half-open, 2=open)",
)

ai_sre_daily_cost_usd = Gauge(
    "ai_sre_daily_cost_usd",
    "Current daily API cost in USD",
)

# --- Accuracy Feedback Metrics ---

ai_sre_feedback_total = Counter(
    "ai_sre_feedback_total",
    "Total human feedback received on advisories",
    labelnames=["feedback_type"],
)

ai_sre_accuracy_ratio = Gauge(
    "ai_sre_accuracy_ratio",
    "Rolling accuracy ratio based on human feedback",
    labelnames=["agent_role"],
)

# --- System Info ---

ai_sre_system_info = Info(
    "ai_sre_system",
    "AI SRE system build information",
)
