apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosmos-node-credentials
  namespace: cosmos
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: cosmos-node-credentials
    creationPolicy: Owner
  data:
    - secretKey: node-key
      remoteRef:
        key: /chains/cosmos/node-credentials
        property: node-key
    - secretKey: priv-validator-key
      remoteRef:
        key: /chains/cosmos/node-credentials
        property: priv-validator-key
