apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cosmos
  namespace: cosmos
  labels:
    app.kubernetes.io/name: cosmos
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cosmos
