# Staging environment overrides for RabbitMQ Operator
# Production-like configuration

rabbitmq-cluster-operator:
  clusterOperator:
    replicaCount: 2

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  msgTopologyOperator:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
