---
# ConstraintTemplate: Block :latest image tag
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sblocklatesttag
  annotations:
    description: Blocks containers using the :latest tag or no tag
spec:
  crd:
    spec:
      names:
        kind: K8sBlockLatestTag
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedRegistries:
              type: array
              items:
                type: string
              description: "Registries exempt from this policy"
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sblocklatesttag

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          has_latest_tag(container.image)
          not is_exempt_registry(container.image)
          msg := sprintf("Container %v uses :latest tag or no tag. Use specific version tags. Image: %v", [container.name, container.image])
        }

        violation[{"msg": msg}] {
          container := input.review.object.spec.initContainers[_]
          has_latest_tag(container.image)
          not is_exempt_registry(container.image)
          msg := sprintf("Init container %v uses :latest tag or no tag. Use specific version tags. Image: %v", [container.name, container.image])
        }

        has_latest_tag(image) {
          endswith(image, ":latest")
        }

        has_latest_tag(image) {
          not contains(image, ":")
          not contains(image, "@sha256:")
        }

        is_exempt_registry(image) {
          allowed := input.parameters.allowedRegistries[_]
          startswith(image, allowed)
        }
---
# Constraint: Block latest tags
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockLatestTag
metadata:
  name: block-latest-tag
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-system
      - kube-public
      - gatekeeper-system
  parameters:
    allowedRegistries:
      # AWS system registries (they use digest-based pulls)
      - "602401143452.dkr.ecr"
      - "registry.k8s.io"
