---
apiVersion: platform.io/v1
kind: VersionManifest
metadata:
  environment: prod
  lastUpdated: "2026-02-03T00:00:00Z"
  updatedBy: platform-team
spec:
  defaults:
    helm:
      chart: helm/app
      version: "0.2.0"
    image:
      repository: "${ECR_REGISTRY}"

  applications:
    mono:
      image:
        tag: "0.1.0"
        # digest: sha256:...  # Uncomment and set for immutable prod deploys
      replicas: 3
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 1Gi

    chains:
      image:
        tag: "0.1.0"
      replicas: 3

    direct:
      image:
        tag: "0.1.0"
      replicas: 3

    protocols:
      image:
        tag: "0.1.0"
      replicas: 3

    listeners:
      image:
        tag: "0.1.0"
      replicas: 3
