---
apiVersion: platform.io/v1
kind: VersionManifest
metadata:
  environment: integration
  lastUpdated: "2026-02-03T00:00:00Z"
  updatedBy: platform-team
spec:
  defaults:
    helm:
      chart: helm/app
      version: "0.2.0"
    image:
      repository: "${ECR_REGISTRY}"

  applications:
    mono:
      image:
        tag: "0.1.0"
      replicas: 2

    chains:
      image:
        tag: "0.1.0"
      replicas: 2

    direct:
      image:
        tag: "0.1.0"
      replicas: 2

    protocols:
      image:
        tag: "0.1.0"
      replicas: 2

    listeners:
      image:
        tag: "0.1.0"
      replicas: 2
