apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: avalanche
  namespace: avalanche
  labels:
    app.kubernetes.io/name: avalanche
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: avalanche
