apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cosmos-listener
  namespace: cosmos
  labels:
    app.kubernetes.io/name: cosmos-listener
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cosmos-listener
