apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tron
  namespace: tron
  labels:
    app.kubernetes.io/name: tron
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tron
