# ---------------------------------------------------------------------------------------------------------------------
# ClusterMesh Connect — Catalog Unit
# ---------------------------------------------------------------------------------------------------------------------
# Creates cross-cluster connection secrets for Cilium ClusterMesh.
# This is a global resource that connects all regional clusters within an environment.
#
# Prerequisites:
#   - Cilium with ClusterMesh enabled in all target regions
#   - ClusterMesh API server NLBs provisioned and accessible
#   - TLS certificates available (auto-generated by Cilium Helm)
#
# NOTE: This unit is deployed at the _global level since it requires outputs
# from multiple regional Cilium deployments. In practice, you run this once
# per cluster, passing the OTHER cluster(s) as remote_clusters.
# ---------------------------------------------------------------------------------------------------------------------

terraform {
  source = "${get_repo_root()}/terraform/modules/clustermesh-connect"
}

locals {
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  region_vars  = read_terragrunt_config(find_in_parent_folders("region.hcl"))

  environment = local.account_vars.locals.environment
  aws_region  = local.region_vars.locals.aws_region
}

# ---------------------------------------------------------------------------------------------------------------------
# DEPENDENCIES: Regional Cilium deployments
# ---------------------------------------------------------------------------------------------------------------------
# Each region's Cilium outputs the ClusterMesh API server endpoint and TLS certs.
# We depend on the local region's Cilium to ensure it is ready before connecting.
# ---------------------------------------------------------------------------------------------------------------------

dependency "cilium" {
  config_path = "../cilium"

  mock_outputs = {
    clustermesh_enabled = true
    cluster_mesh_name   = "staging-euw1"
    cluster_mesh_id     = 1
  }

  mock_outputs_allowed_terraform_commands = ["init", "validate", "plan"]
  mock_outputs_merge_strategy_with_state  = "shallow"
}

# ---------------------------------------------------------------------------------------------------------------------
# MODULE INPUTS
# ---------------------------------------------------------------------------------------------------------------------
# remote_clusters is populated externally (e.g., via a data source or manual config)
# after the ClusterMesh API servers are running in all regions. The TLS certificates
# must be exchanged out-of-band or via a shared secrets store.
# ---------------------------------------------------------------------------------------------------------------------

inputs = {
  # Remote clusters will be configured post-deployment when TLS certs are available.
  # Example structure (populated via environment-specific override):
  # remote_clusters = {
  #   "staging-euc1" = {
  #     endpoint = "clustermesh-apiserver.staging-euc1.internal:2379"
  #     ca_cert  = data.aws_secretsmanager_secret_version.remote_ca.secret_string
  #     tls_cert = data.aws_secretsmanager_secret_version.remote_cert.secret_string
  #     tls_key  = data.aws_secretsmanager_secret_version.remote_key.secret_string
  #   }
  # }
  remote_clusters = {}
}
