apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.secretStore.name }}
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: helm
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
            namespace: {{ .Values.serviceAccount.namespace }}
