apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitcoin-rpc-credentials
  namespace: chains
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: bitcoin-rpc-credentials
    creationPolicy: Owner
  data:
    - secretKey: rpcuser
      remoteRef:
        key: /chains/bitcoin/rpc-credentials
        property: rpcuser
    - secretKey: rpcpassword
      remoteRef:
        key: /chains/bitcoin/rpc-credentials
        property: rpcpassword
