{{- if .Values.loki.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-s3-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "loki-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: loki
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # Refresh interval - check for updates every 5 minutes
  refreshInterval: 5m

  # Secret store reference
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  # Target secret configuration
  target:
    name: loki-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain

    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: loki
          app.kubernetes.io/component: storage

      # Template the secret data
      data:
        S3_ACCESS_KEY: |-
          {{ `{{ .access_key_id }}` }}
        S3_SECRET_KEY: |-
          {{ `{{ .secret_access_key }}` }}

        # Optional: bucket configuration
        S3_BUCKET_CHUNKS: |-
          {{ `{{ .bucket_chunks | default "loki-chunks" }}` }}
        S3_BUCKET_RULER: |-
          {{ `{{ .bucket_ruler | default "loki-ruler" }}` }}
        S3_BUCKET_ADMIN: |-
          {{ `{{ .bucket_admin | default "loki-admin" }}` }}

  # Data from AWS Parameter Store
  dataFrom:
    - extract:
        # Path to parameter store values
        # Expected parameters:
        # /observability/loki/s3/access_key_id
        # /observability/loki/s3/secret_access_key
        # /observability/loki/s3/bucket_chunks
        # /observability/loki/s3/bucket_ruler
        # /observability/loki/s3/bucket_admin
        key: /observability/loki/s3

---
# Alternative: Direct data mapping (if not using dataFrom)
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: loki-s3-credentials
#   namespace: {{ .Release.Namespace }}
# spec:
#   refreshInterval: 5m
#   secretStoreRef:
#     name: aws-parameter-store
#     kind: ClusterSecretStore
#
#   target:
#     name: loki-s3-credentials
#     creationPolicy: Owner
#
#   data:
#     - secretKey: S3_ACCESS_KEY
#       remoteRef:
#         key: /observability/loki/s3/access_key_id
#
#     - secretKey: S3_SECRET_KEY
#       remoteRef:
#         key: /observability/loki/s3/secret_access_key
#
#     - secretKey: S3_BUCKET_CHUNKS
#       remoteRef:
#         key: /observability/loki/s3/bucket_chunks
#
#     - secretKey: S3_BUCKET_RULER
#       remoteRef:
#         key: /observability/loki/s3/bucket_ruler
#
#     - secretKey: S3_BUCKET_ADMIN
#       remoteRef:
#         key: /observability/loki/s3/bucket_admin

---
# Service Account for Loki with IRSA (IAM Roles for Service Accounts)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  annotations:
    # IRSA annotation - replace with actual IAM role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.awsAccountId | default "ACCOUNT_ID" }}:role/loki-s3-access
  labels:
    app.kubernetes.io/name: {{ include "loki-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: loki

{{- end }}
