{{- if .Values.networkPolicy.enabled }}
---
# Network Policy: Fluent Bit egress to Loki
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fluent-bit-to-loki
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: log-collector
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit

  policyTypes:
    - Egress

  egress:
    # Allow Fluent Bit to send logs to Loki gateway
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
              app.kubernetes.io/component: gateway
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 80

    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Allow access to Kubernetes API for metadata
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
      ports:
        - protocol: TCP
          port: 443

---
# Network Policy: Loki Gateway ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-gateway-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: gateway

  policyTypes:
    - Ingress

  ingress:
    # Allow Fluent Bit to push logs
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: fluent-bit
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 80

    # Allow Grafana to query logs
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 80

    # Allow Prometheus to scrape metrics
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 3100

---
# Network Policy: Loki Read component
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-read
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: read
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: read

  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Allow gateway to query read components
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
              app.kubernetes.io/component: gateway
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9095

    # Allow Prometheus scraping
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 3100

  egress:
    # Allow queries to other Loki components
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9095

    # Allow S3 access (external)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443

    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53

---
# Network Policy: Loki Write component
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-write
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: write
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: write

  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Allow gateway to send logs to write components
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
              app.kubernetes.io/component: gateway
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9095

    # Allow Prometheus scraping
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 3100

  egress:
    # Allow communication with other Loki components
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9095

    # Allow S3 access
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443

    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53

---
# Network Policy: Loki Backend component
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: backend

  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Allow gateway communication
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
              app.kubernetes.io/component: gateway
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9095

    # Allow Prometheus scraping
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 3100

  egress:
    # Allow communication with other Loki components
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9095

    # Allow S3 access (for compactor)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443

    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53

{{- end }}
