apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ethereum-listener
  namespace: ethereum
  labels:
    app.kubernetes.io/name: ethereum-listener
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ethereum-listener
