{{- if .Values.externalSecrets.enabled }}
{{- if .Values.externalSecrets.s3Credentials.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pyroscope-s3-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pyroscope.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # Refresh interval for secret synchronization
  refreshInterval: 1h

  # Reference to the SecretStore
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}

  # Target secret to create
  target:
    name: pyroscope-s3-credentials
    creationPolicy: Owner

    template:
      type: Opaque

      metadata:
        labels:
          app.kubernetes.io/name: {{ include "pyroscope.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: storage

      data:
        # S3 credentials for Pyroscope
        AWS_ACCESS_KEY_ID: "{{ `{{ .access_key_id }}` }}"
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .secret_access_key }}` }}"

        # Additional configuration for Pyroscope
        AWS_REGION: "{{ .Values.pyroscope.pyroscope.storage.s3.region }}"
        S3_BUCKET: "{{ .Values.pyroscope.pyroscope.storage.s3.bucket }}"

  # Data to fetch from external secret store
  dataFrom:
    - extract:
        key: /gaming-platform/prod/pyroscope/s3-credentials

  # Alternative: individual secret references
  # data:
  #   - secretKey: access_key_id
  #     remoteRef:
  #       key: /gaming-platform/prod/pyroscope/s3-access-key
  #
  #   - secretKey: secret_access_key
  #     remoteRef:
  #       key: /gaming-platform/prod/pyroscope/s3-secret-key

---
# IRSA Service Account for Pyroscope components
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pyroscope-storage
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pyroscope.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: storage
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    # IRSA annotation for AWS IAM role
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId | default "ACCOUNT_ID" }}:role/pyroscope-storage-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/token-expiration: "86400"

---
# IAM Policy Document (for reference - create via Terraform)
# This shows the required IAM permissions for Pyroscope S3 access
apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-iam-policy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pyroscope.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: documentation
  annotations:
    description: "IAM policy required for Pyroscope S3 access - create via Terraform"
data:
  policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "PyroscopeS3ListBucket",
          "Effect": "Allow",
          "Action": [
            "s3:ListBucket",
            "s3:GetBucketLocation"
          ],
          "Resource": [
            "arn:aws:s3:::{{ .Values.pyroscope.pyroscope.storage.s3.bucket }}"
          ]
        },
        {
          "Sid": "PyroscopeS3ObjectAccess",
          "Effect": "Allow",
          "Action": [
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject",
            "s3:ListMultipartUploadParts",
            "s3:AbortMultipartUpload"
          ],
          "Resource": [
            "arn:aws:s3:::{{ .Values.pyroscope.pyroscope.storage.s3.bucket }}/*"
          ]
        },
        {
          "Sid": "PyroscopeS3Encryption",
          "Effect": "Allow",
          "Action": [
            "kms:Decrypt",
            "kms:Encrypt",
            "kms:GenerateDataKey"
          ],
          "Resource": [
            "arn:aws:kms:{{ .Values.pyroscope.pyroscope.storage.s3.region }}:{{ .Values.aws.accountId | default "ACCOUNT_ID" }}:key/*"
          ],
          "Condition": {
            "StringEquals": {
              "kms:ViaService": [
                "s3.{{ .Values.pyroscope.pyroscope.storage.s3.region }}.amazonaws.com"
              ]
            }
          }
        }
      ]
    }

  trust-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "arn:aws:iam::{{ .Values.aws.accountId | default "ACCOUNT_ID" }}:oidc-provider/oidc.eks.{{ .Values.pyroscope.pyroscope.storage.s3.region }}.amazonaws.com/id/{{ .Values.aws.oidcProviderId | default "OIDC_PROVIDER_ID" }}"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "StringEquals": {
              "oidc.eks.{{ .Values.pyroscope.pyroscope.storage.s3.region }}.amazonaws.com/id/{{ .Values.aws.oidcProviderId | default "OIDC_PROVIDER_ID" }}:sub": "system:serviceaccount:{{ .Release.Namespace }}:pyroscope-storage",
              "oidc.eks.{{ .Values.pyroscope.pyroscope.storage.s3.region }}.amazonaws.com/id/{{ .Values.aws.oidcProviderId | default "OIDC_PROVIDER_ID" }}:aud": "sts.amazonaws.com"
            }
          }
        }
      ]
    }

{{- end }}
{{- end }}
