"""Prometheus metrics for the alert ingestion pipeline."""

from prometheus_client import Counter, Histogram

alerts_received_total = Counter(
    "ai_sre_alerts_received_total",
    "Total alerts received from Alertmanager webhooks",
    ["cluster", "severity"],
)

alerts_deduplicated_total = Counter(
    "ai_sre_alerts_deduplicated_total",
    "Total alerts deduplicated (not triggering new investigation)",
)

agent_investigation_duration_seconds = Histogram(
    "ai_sre_agent_investigation_duration_seconds",
    "Duration of agent investigations in seconds",
    ["agent"],
    buckets=[1, 5, 10, 30, 60, 120, 300, 600],
)

advisory_generated_total = Counter(
    "ai_sre_advisory_generated_total",
    "Total advisories generated by agents",
    ["agent"],
)

alert_enrichment_duration_seconds = Histogram(
    "ai_sre_alert_enrichment_duration_seconds",
    "Duration of alert enrichment in seconds",
    buckets=[0.1, 0.5, 1, 2, 5, 10],
)

webhook_requests_total = Counter(
    "ai_sre_webhook_requests_total",
    "Total webhook requests received",
    ["status"],
)
